name: first workflow 
on: 
    push: 
        branches: 
            - main

jobs:
    first_workflow_job:
        runs-on: ubuntu-latest
        steps:
            - name: list files
              run: echo "CICD" 

